// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo28gzrg_AmzRhgXSPqhQnOpxPY_nkas8',
    appId: '1:744906428261:web:d9bb5c6aa08c8e0451db8c',
    messagingSenderId: '744906428261',
    projectId: 'lms-d1c0f',
    authDomain: 'lms-d1c0f.firebaseapp.com',
    storageBucket: 'lms-d1c0f.appspot.com',
    measurementId: 'G-1F0L08RR4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXy1n3V5HmPu1R2vhccMugulhgdkiVkY',
    appId: '1:744906428261:android:c044fb6f0212b23651db8c',
    messagingSenderId: '744906428261',
    projectId: 'lms-d1c0f',
    storageBucket: 'lms-d1c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKsZJcrm-3FP3zjT8ua5R6Ydj2UM6YaZ4',
    appId: '1:744906428261:ios:e02d3e8943050aaf51db8c',
    messagingSenderId: '744906428261',
    projectId: 'lms-d1c0f',
    storageBucket: 'lms-d1c0f.appspot.com',
    iosClientId: '744906428261-l5vlqftrh8p1343vgtb7tk9lad2b6ee3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKsZJcrm-3FP3zjT8ua5R6Ydj2UM6YaZ4',
    appId: '1:744906428261:ios:e02d3e8943050aaf51db8c',
    messagingSenderId: '744906428261',
    projectId: 'lms-d1c0f',
    storageBucket: 'lms-d1c0f.appspot.com',
    iosClientId: '744906428261-l5vlqftrh8p1343vgtb7tk9lad2b6ee3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
