// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZiavE6m_qsofAXzoTGFMZ6zJANIlDFGw',
    appId: '1:168817670383:web:6d74813140d25c743c431a',
    messagingSenderId: '168817670383',
    projectId: 'flutter-lms-1f569',
    authDomain: 'flutter-lms-1f569.firebaseapp.com',
    storageBucket: 'flutter-lms-1f569.appspot.com',
    measurementId: 'G-YZ48LWHXJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKWEnCI20hjppN3LBO1DrQE31Os4gepMM',
    appId: '1:168817670383:android:a67864799b18477e3c431a',
    messagingSenderId: '168817670383',
    projectId: 'flutter-lms-1f569',
    storageBucket: 'flutter-lms-1f569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFWwiWvSoDSziCCvSiIwPxuLkipo0C3A',
    appId: '1:168817670383:ios:d3980a87961dcdfe3c431a',
    messagingSenderId: '168817670383',
    projectId: 'flutter-lms-1f569',
    storageBucket: 'flutter-lms-1f569.appspot.com',
    iosClientId: '168817670383-f1qjbi4cq3dt21k3l6e0fnaljh0h3o4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFWwiWvSoDSziCCvSiIwPxuLkipo0C3A',
    appId: '1:168817670383:ios:d3980a87961dcdfe3c431a',
    messagingSenderId: '168817670383',
    projectId: 'flutter-lms-1f569',
    storageBucket: 'flutter-lms-1f569.appspot.com',
    iosClientId: '168817670383-f1qjbi4cq3dt21k3l6e0fnaljh0h3o4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
